#!/usr/bin/env ruby

# This file was placed here by GitLab. It makes sure that your pushed commits
# will be processed properly.

refs = ARGF.read
key_id  = ENV['GL_ID']
repo_path = Dir.pwd

# reset GL_ID env since we already got its value
ENV['GL_ID'] = nil

require_relative '../lib/gitlab_custom_hook'
require_relative '../lib/gitlab_sync'

GitlabSync.new(repo_path, refs).exec
# if GitlabPostReceive.new(repo_path, key_id, refs).exec &&
#     GitlabCustomHook.new.post_receive(refs, repo_path)
#   exit 0
# else
#   exit 1
# end

exit 0
